services:
  app:
    command: sleep infinity
    volumes:
      - .:/workspaces/hookdiff:cached
      - devcontainer_node_modules:/workspaces/hookdiff/frontend/node_modules
      - devcontainer_backend_venv:/workspaces/hookdiff/backend/.venv
    working_dir: /workspaces/hookdiff

volumes:
  devcontainer_node_modules:
  devcontainer_backend_venv:
